<?php

/**
 * @author www.intercambiosvirtuales.org
 * @copyright 2010
 */



?>
<div id="usuario">

</div>
<div class="producto">
    <b><?echo $clasificado->titulo;?></b>
    <table class="atributos">
        <tr>
            <td class="atributo">Categoria:</td>
            <td class="atributo">categoria</td>
        </tr>
        <tr>
            <td class="atributo">Publicado:</td>
            <td class="atributo"><span class="when"></span>in <span class="where"></span></td>
        </tr>
        <tr>
            <td class="atributo">Descripcion:</td>
            <td class="atributo"><? echo $clasificado->contenido; ?></td>
        </tr>
    </table>
</div>