
<div id='info'>
        <h1>Bienvenido a Clasificados Buyigo</h1>
        <p>Ya puedes empezar a buscar aquellos que necesitas o publicar lo que deseas vender</p>
        <p>Buyigo Clasificados es un sistema de publicacion de clasificados para los usuarios de facebook
        que permite la publicacion de anuncios. 
            
        <p>y muchas cosas más. Buyico Clasificados puede ser la solución que esta buscando. </p>
        <fb:prompt-permission perms="email, read_stream, publish_stream, offline_access, share_item">Buyigo Clasificados require de los siguientes permisos para su corecto funcionamiento</fb:prompt-permission>
 </div>