<?php

/**
 * @author www.intercambiosvirtuales.org
 * @copyright 2010
 */


?>
<div class="content">
<?php foreach ($clasificados->items as $item) : ?>
    <li>
        <strong><?php echo $item->titulo ?> - <?php echo $item->contenido ?></strong>
    </li>
    <?php endforeach; ?>
    </ul>
 
 <?php if($clasificados->prev) echo link_to(array("clasificados/index/$clasificados->prev/", '<< Anterior |')); ?>
<?php if($clasificados->next) echo link_to(array("menus/index/$clasificados->next/", 'Próximo >>')); ?>
</div>